# Generated by Django 6.0.8 on 2026-09-27 12:19

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Demo/sample content created for development. Shown with a 'Sample' badge.")),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('paper_type', models.CharField(choices=[('previous_year', 'Previous year paper'), ('sample', 'Sample paper'), ('model', 'Model paper'), ('practice', 'Practice paper'), ('chapter_wise', 'Chapter-wise paper'), ('pre_board', 'Pre-board paper')], db_index=True, default='sample', max_length=20)),
                ('exam_type', models.CharField(choices=[('annual', 'Annual / main examination'), ('supplementary', 'Supplementary / compartment'), ('term_1', 'Term 1'), ('term_2', 'Term 2'), ('pre_board', 'Pre-board'), ('other', 'Other')], default='annual', max_length=20)),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, upload_to='papers/%Y/', validators=[core.validators.PDFValidator()])),
                ('solution_pdf', models.FileField(blank=True, upload_to='papers/solutions/%Y/', validators=[core.validators.PDFValidator()])),
                ('total_marks', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0, editable=False)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('chapter', models.ForeignKey(blank=True, help_text='Only for chapter-wise papers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='boards.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='boards.subject')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreviousYearPaper',
            fields=[
            ],
            options={
                'verbose_name': 'previous year paper',
                'verbose_name_plural': 'previous year papers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('papers.questionpaper',),
        ),
        migrations.AddIndex(
            model_name='questionpaper',
            index=models.Index(fields=['paper_type', 'year'], name='papers_ques_paper_t_46adbd_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpaper',
            index=models.Index(fields=['subject', 'paper_type', 'is_published'], name='papers_ques_subject_6de822_idx'),
        ),
    ]
