# Generated by Django 6.0.8 on 2026-09-27 12:19

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='boards.subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Demo/sample content created for development. Shown with a 'Sample' badge.")),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice (single answer)'), ('multi', 'Multiple choice (multiple answers)'), ('true_false', 'True / False'), ('numeric', 'Numerical answer'), ('fill_blank', 'Fill in the blank'), ('short', 'Short answer'), ('long', 'Long answer')], default='mcq', max_length=12)),
                ('text', models.TextField(verbose_name='question')),
                ('image', models.ImageField(blank=True, upload_to='questions/%Y/', validators=[core.validators.ImageValidator()])),
                ('answer', models.TextField(blank=True, help_text="Model answer. For numeric questions the number; for fill-in-the-blank, accepted answers separated by '|'.")),
                ('explanation', models.TextField(blank=True, help_text='Step-by-step explanation (Markdown)')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='medium', max_length=10)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('numeric_tolerance', models.FloatField(default=0.01, help_text='Allowed absolute error for numeric answers')),
                ('source', models.CharField(choices=[('manual', 'Created by editor'), ('previous_year', 'From a previous-year paper'), ('ai', 'AI generated (reviewed)')], default='manual', max_length=15)),
                ('is_important', models.BooleanField(db_index=True, default=False, help_text='Editor-marked important question')),
                ('fingerprint', models.CharField(db_index=True, editable=False, help_text='Hash of normalized text for repeat detection', max_length=64)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='boards.chapter')),
                ('concepts', models.ManyToManyField(blank=True, related_name='questions', to='questions.concept')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='boards.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='boards.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True, help_text='Examination year (copied from the paper when blank)')),
                ('question_number', models.CharField(blank=True, max_length=20)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='papers.questionpaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='questions.question')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('subject', 'slug'), name='unique_concept_per_subject'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'chapter', 'is_published'], name='questions_q_subject_6ae3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'difficulty'], name='questions_q_questio_086a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='questionappearance',
            index=models.Index(fields=['question', 'year'], name='questions_q_questio_823107_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionappearance',
            constraint=models.UniqueConstraint(fields=('question', 'paper'), name='unique_question_per_paper'),
        ),
    ]
