# Generated by Django 6.0.8 on 2026-09-27 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('testengine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_type', models.CharField(db_index=True, max_length=20)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('attempted', models.PositiveSmallIntegerField(default=0)),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('incorrect', models.PositiveSmallIntegerField(default=0)),
                ('skipped', models.PositiveSmallIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('time_seconds', models.PositiveIntegerField(default=0)),
                ('recorded_on', models.DateField(db_index=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='testengine.testattempt')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_records', to='boards.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='boards.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_on'],
                'indexes': [models.Index(fields=['user', 'subject'], name='analytics_p_user_id_518b04_idx'), models.Index(fields=['user', 'chapter'], name='analytics_p_user_id_c6d068_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('login', 'Signed in'), ('view_paper', 'Viewed paper'), ('download_paper', 'Downloaded paper'), ('view_material', 'Viewed study material'), ('view_question', 'Viewed question'), ('view_chapter', 'Viewed chapter'), ('start_test', 'Started test'), ('submit_test', 'Submitted test'), ('scan', 'Scanned a question'), ('ask_ai', 'Asked the AI assistant'), ('search', 'Searched'), ('bookmark', 'Bookmarked')], db_index=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_39836b_idx'), models.Index(fields=['user', 'activity_type'], name='analytics_u_user_id_266824_idx')],
            },
        ),
    ]
