# Generated by Django 6.0.8 on 2026-09-27 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('papers', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Demo/sample content created for development. Shown with a 'Sample' badge.")),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Shown before the test starts (Markdown)')),
                ('test_type', models.CharField(choices=[('chapter', 'Chapter test'), ('subject', 'Subject test'), ('board', 'Board test'), ('previous_year', 'Previous year test'), ('practice', 'Practice test'), ('mock', 'Full-length mock test')], db_index=True, default='practice', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('pass_percentage', models.PositiveSmallIntegerField(default=33)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('show_explanations', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='boards.board')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='boards.chapter')),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='boards.classlevel', verbose_name='class')),
                ('paper', models.ForeignKey(blank=True, help_text='Source paper for previous-year tests', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='papers.questionpaper')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='boards.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto-submitted (time up)')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('question_order', models.JSONField(default=list, help_text='TestQuestion ids in display order')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('percentage', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('incorrect_count', models.PositiveSmallIntegerField(default=0)),
                ('unanswered_count', models.PositiveSmallIntegerField(default=0)),
                ('ungraded_count', models.PositiveSmallIntegerField(default=0, help_text='Subjective answers not auto-graded')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='testengine.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, help_text="Override the question's default marks", max_digits=5, null=True)),
                ('negative_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_links', to='questions.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='testengine.test')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_answer', models.TextField(blank=True)),
                ('is_marked_for_review', models.BooleanField(default=False)),
                ('visited', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField(help_text='Null = unanswered or not auto-graded', null=True)),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('selected_options', models.ManyToManyField(blank=True, to='questions.questionoption')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testengine.testattempt')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testengine.testquestion')),
            ],
            options={
                'ordering': ['attempt', 'test_question__order'],
            },
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', through='testengine.TestQuestion', to='questions.question'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', 'status'], name='testengine__user_id_5962e9_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['user', '-started_at'], name='testengine__user_id_b95634_idx'),
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.UniqueConstraint(fields=('test', 'question'), name='unique_question_per_test'),
        ),
        migrations.AddConstraint(
            model_name='testanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'test_question'), name='unique_answer_per_question'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['test_type', 'is_published'], name='testengine__test_ty_018a40_idx'),
        ),
    ]
