"""
Official subject catalog for each board's board-exam classes (loaded by `manage.py load_subjects`).

Only the main academic subjects are listed; add more here (or in Django Admin) as needed.
Each entry is (name, official subject code or "").
"""

CLASS_NAMES = {10: "Class 10", 12: "Class 12"}

CATALOG = {
    "CBSE": {
        10: [
            ("English", "184"),  # English Language and Literature
            ("Hindi Course A", "002"),
            ("Hindi Course B", "085"),
            ("Mathematics", "041"),  # Mathematics Standard
            ("Mathematics Basic", "241"),
            ("Science", "086"),
            ("Social Science", "087"),
            ("Sanskrit", "122"),
            ("Computer Applications", "165"),
            ("Information Technology", "402"),
            ("Artificial Intelligence", "417"),
        ],
        12: [
            ("English Core", "301"),
            ("Hindi Core", "302"),
            ("Physics", "042"),
            ("Chemistry", "043"),
            ("Biology", "044"),
            ("Mathematics", "041"),
            ("Applied Mathematics", "241"),
            ("Accountancy", "055"),
            ("Business Studies", "054"),
            ("Economics", "030"),
            ("History", "027"),
            ("Geography", "029"),
            ("Political Science", "028"),
            ("Psychology", "037"),
            ("Sociology", "039"),
            ("Computer Science", "083"),
            ("Informatics Practices", "065"),
            ("Physical Education", "048"),
        ],
    },
    "MSBSHSE": {
        10: [
            ("English (First Language)", "03"),
            ("English (Second or Third Language)", "17"),
            ("Hindi (Second or Third Language)", "15"),
            ("Marathi (First Language)", "01"),
            ("Mathematics Part I", "71"),
            ("Mathematics Part II", "71"),
            ("Science and Technology Part 1", "72"),
            ("Science and Technology Part 2", "72"),
            ("Social Sciences Part I (History and Political Science)", "73"),
            ("Social Sciences Part II (Geography)", "73"),
        ],
        12: [
            ("Agriculture Micro Irrigation Technician", "G8"),
            ("Agriculture Science and Technology", "75"),
            ("Animal Science and Technology", ""),
            ("Arabic", "36"),
            ("Ardhamagadhi", ""),
            ("Automotive Service Technician", "G3"),
            ("Beauty and Wellness", "G6"),
            ("Bengali", ""),
            ("Biology", "56"),
            ("Book-Keeping and Accountancy", "50"),
            ("Chemistry", "55"),
            ("Child Development", "43"),
            ("Chinese", ""),
            ("Co-operation", "53"),
            ("Defence Studies", "77"),
            ("Economics", "49"),
            ("Education", "78"),
            ("English", "01"),
            ("Field Technician (Electronics and Home Appliances)", "F6"),
            ("Food Science and Technology", "62"),
            ("French", ""),
            ("Geography", "39"),
            ("Geology", ""),
            ("German", ""),
            ("Gujarati", ""),
            ("Healthcare (General Duty Assistant)", "G5"),
            ("Hindi", ""),
            ("History", "38"),
            ("History and Appreciation of Arts", ""),
            ("History and Development of Indian Music", ""),
            ("Home Management", "61"),
            ("Kannada", ""),
            ("Library and Information Science", "85"),
            ("Logic", ""),
            ("Maharashtri Prakrit", ""),
            ("Malayalam", ""),
            ("Marathi", ""),
            ("Mathematics and Statistics (Arts and Science)", "40"),
            ("Mathematics and Statistics (Commerce)", "88"),
            ("Multiskill Technician (Electrical)", "E3"),
            ("Multiskill Technician (Food Processing)", "E6"),
            ("Organisation of Commerce and Management", "51"),
            ("Pali", ""),
            ("Percussion Instruments", ""),
            ("Persian", "37"),
            ("Philosophy", ""),
            ("Physical Education (Sports) Fitness Trainer", "G7"),
            ("Physics", "54"),
            ("Plumbing Technician", "G2"),
            ("Political Science", "42"),
            ("Power Distribution Lineman", "F8"),
            ("Psychology", "48"),
            ("Punjabi", ""),
            ("Retail Sales Associate", "G4"),
            ("Russian", ""),
            ("Sanskrit", ""),
            ("Secretarial Practice", "52"),
            ("Sindhi", ""),
            ("Sociology", "45"),
            ("Spanish", ""),
            ("Specialized Sewing Machine Operator", "G1"),
            ("Tamil", ""),
            ("Telugu", ""),
            ("Textiles", "44"),
            ("Tourism and Hospitality (Customer Service Executive)", "G9"),
            ("Urdu", "05"),
        ],
    },
    "ICSE": {
        10: [
            ("Biology", ""),
            ("Chemistry", ""),
            ("Commercial Applications", ""),
            ("Commercial Studies", ""),
            ("Computer Applications", ""),
            ("Economic Applications", ""),
            ("Economics", ""),
            ("English Language", ""),
            ("Environmental Science", ""),
            ("Geography", ""),
            ("Hindi", ""),
            ("History & Civics", ""),
            ("Home Science", ""),
            ("Literature in English", ""),
            ("Mathematics", ""),
            ("Physics", ""),
        ],
        12: [
            ("Accounts", ""),
            ("Biology", ""),
            ("Business Studies", ""),
            ("Chemistry", ""),
            ("Commerce", ""),
            ("Computer Science", ""),
            ("Economics", ""),
            ("Elective English", ""),
            ("English Language", ""),
            ("Environmental Science", ""),
            ("Geography", ""),
            ("Hindi", ""),
            ("History", ""),
            ("Home Science", ""),
            ("Legal Studies", ""),
            ("Literature in English", ""),
            ("Mathematics", ""),
            ("Physics", ""),
            ("Political Science", ""),
            ("Psychology", ""),
            ("Sociology", ""),
        ],
    },
    "BSEB": {
        10: [
            ("Mathematics", "110"),
            ("Science", "112"),
            ("Hindi (MIL)", "101"),
            ("Bangla (MIL)", "102"),
            ("Urdu (MIL)", "103"),
            ("Maithili (MIL)", "104"),
            ("Sanskrit (SIL)", "105"),
            ("Hindi (SIL)", "106"),
            ("Arabic (SIL)", "107"),
            ("Persian (SIL)", "108"),
            ("Bhojpuri (SIL)", "109"),
            ("Social Science", "111"),
            ("English", "113"),
            ("Advanced Mathematics", "114"),
            ("Commerce", "115"),
            ("Fine Arts", "117"),
            ("Home Science", "118"),
            ("Dance", "119"),
            ("Music", "120"),
            ("Persian (Optional)", "121"),
            ("Sanskrit (Optional)", "122"),
            ("Arabic (Optional)", "123"),
            ("Maithili (Optional)", "124"),
        ],
        12: [
            ("Physics", "117"),
            ("Chemistry", "118"),
            ("Mathematics", "121"),
            ("Computer Science", "122"),
            ("Business Studies", "217"),
            ("Entrepreneurship", "218"),
            ("Economics (Commerce)", "219"),
            ("Accountancy", "220"),
            ("Political Science", "322"),
            ("Geography", "323"),
            ("English", "105"),
            ("Hindi", "106"),
            ("Urdu", "107"),
            ("Maithili", "108"),
            ("Sanskrit", "109"),
            ("Prakrit", "110"),
            ("Magahi", "111"),
            ("Bhojpuri", "112"),
            ("Arabic", "113"),
            ("Persian", "114"),
            ("Pali", "115"),
            ("Bangla", "116"),
            ("Biology", "119"),
            ("Agriculture", "120"),
            ("Multimedia & Web Technology", "123"),
            ("Yoga & Physical Education", "317"),
            ("Music", "318"),
            ("Home Science", "319"),
            ("Philosophy", "320"),
            ("History", "321"),
            ("Psychology", "324"),
            ("Sociology", "325"),
            ("Economics", "326"),
        ],
    },
    "UPMSP": {
        10: [
            ("Drawing", "936"),
            ("Human Science", "942"),
            ("Disaster Management", "978"),
        ],
    },
    "GSEB": {
        10: [
            ("Arabic", "20"),
            ("English (First Language)", "04"),
            ("English (Second Language)", "16"),
            ("Gujarati (First Language)", "01"),
            ("Gujarati (Second Language)", "13"),
            ("Hindi (First Language)", "02"),
            ("Hindi (Second Language)", "14"),
            ("Marathi (First Language)", "03"),
            ("Mathematics (Basic)", "18"),
            ("Mathematics (Standard)", "12"),
            ("Odia (First Language)", "09"),
            ("Persian", "19"),
            ("Sanskrit", "17"),
            ("Science", "11"),
            ("Sindhi Arabic Script (First Language)", "06"),
            ("Sindhi Arabic Script (Second Language)", "15"),
            ("Sindhi Devanagari Script (First Language)", "06"),
            ("Sindhi Devanagari Script (Second Language)", "15"),
            ("Social Science", "10"),
            ("Telugu (First Language)", "08"),
            ("Urdu (First Language)", "05"),
            ("Urdu (Second Language)", "21"),
        ],
        12: [
            ("Accountancy and Auditing Paper I", "203"),
            ("Accountancy and Auditing Paper II", "205"),
            ("Accountancy and Auditing Paper III", "207"),
            ("Advance Cloth Making", "237"),
            ("Advance House Keeping", "217"),
            ("Animal Reproduction and Artificial Insemination", "171"),
            ("Arabic", "131"),
            ("Bakery and Confectionery", "227"),
            ("Beauty and Wellness", "405"),
            ("Biology", "056"),
            ("Biology and Agricultural Chemistry", "158"),
            ("Chemistry", "052"),
            ("Computer", "331"),
            ("Computer Application", "327"),
            ("Crops I", "165"),
            ("Crops II", "167"),
            ("Dairy Extension and Accounts", "175"),
            ("Drawing", "137"),
            ("Economics", "022"),
            ("Economics and Business Administration", "178"),
            ("Elements of Accountancy", "154"),
            ("English (First Language)", "006"),
            ("English (Second Language)", "013"),
            ("Entrepreneurship", "156"),
            ("Fancy Dress Making", "239"),
            ("Farm Management and Extension", "169"),
            ("Food Processing", "223"),
            ("Geography", "148"),
            ("Gruh Jivan Vidya", "068"),
            ("Gujarati (First Language)", "001"),
            ("Gujarati (Second Language)", "008"),
            ("Health Care", "401"),
            ("Hindi (First Language)", "002"),
            ("Hindi (Second Language)", "009"),
            ("History", "029"),
            ("Interior Decoration", "219"),
            ("Krushi Vidya", "060"),
            ("Marathi (First Language)", "003"),
            ("Mathematics", "050"),
            ("Milk and Milk Products", "173"),
            ("Music", "146"),
            ("Office Method and Correspondence", "181"),
            ("Organisation of Commerce and Management", "046"),
            ("Pashupalan and Dairy Science", "080"),
            ("Pattern Making", "235"),
            ("Persian", "130"),
            ("Philosophy", "136"),
            ("Physics", "054"),
            ("Physics and Mathematics", "254"),
            ("Plant Management", "225"),
            ("Political Science", "023"),
            ("Prakrit", "132"),
            ("Programming Language", "329"),
            ("Psychology", "141"),
            ("Retail", "403"),
            ("Sahkar Panchayat", "111"),
            ("Sanskrit", "129"),
            ("Secretarial Practice", "337"),
            ("Sindhi (First Language)", "005"),
            ("Social Science", "058"),
            ("Social Skill Reportable Metals", "221"),
            ("Sociology", "139"),
            ("Sociology Psychology and Economics", "216"),
            ("Statistics", "135"),
            ("System Analysis and Design", "325"),
            ("Travel and Tourism", "407"),
            ("Urdu (First Language)", "004"),
            ("Van Vidya and Van Aushadhi Vidya", "351"),
            ("Vastra Vidya", "076"),
        ],
    },
    "TNBSE": {
        10: [
            ("Arabic (First Language)", ""),
            ("Arabic (Optional Language)", ""),
            ("English", ""),
            ("French (First Language)", ""),
            ("French (Optional Language)", ""),
            ("Gujarati (First Language)", ""),
            ("Gujarati (Optional Language)", ""),
            ("Hindi (First Language)", ""),
            ("Hindi (Optional Language)", ""),
            ("Kannada (First Language)", ""),
            ("Kannada (Optional Language)", ""),
            ("Malayalam (First Language)", ""),
            ("Malayalam (Optional Language)", ""),
            ("Mathematics", ""),
            ("Sanskrit (First Language)", ""),
            ("Sanskrit (Optional Language)", ""),
            ("Science", ""),
            ("Social Science", ""),
            ("Tamil", ""),
            ("Telugu (First Language)", ""),
            ("Telugu (Optional Language)", ""),
            ("Urdu (First Language)", ""),
            ("Urdu (Optional Language)", ""),
        ],
        12: [
            ("Accountancy", ""),
            ("Advanced Language Tamil", ""),
            ("Agricultural Science", ""),
            ("Arabic", ""),
            ("Basic Automobile Engineering", ""),
            ("Basic Civil Engineering", ""),
            ("Basic Electrical Engineering", ""),
            ("Basic Electronics Engineering", ""),
            ("Basic Mechanical Engineering", ""),
            ("Biochemistry", ""),
            ("Biology", ""),
            ("Botany", ""),
            ("Business Mathematics and Statistics", ""),
            ("Chemistry", ""),
            ("Commerce", ""),
            ("Communicative English", ""),
            ("Computer Applications", ""),
            ("Computer Science", ""),
            ("Computer Technology", ""),
            ("Economics", ""),
            ("Employability Skills", ""),
            ("English", ""),
            ("Ethics and Indian Culture", ""),
            ("Food Service Management", ""),
            ("French", ""),
            ("General Nursing", ""),
            ("Geography", ""),
            ("German", ""),
            ("Hindi", ""),
            ("History", ""),
            ("Home Science", ""),
            ("Kannada", ""),
            ("Malayalam", ""),
            ("Mathematics", ""),
            ("Microbiology", ""),
            ("Nursing Vocational", ""),
            ("Nutrition and Dietetics", ""),
            ("Office Management and Secretaryship", ""),
            ("Physics", ""),
            ("Political Science", ""),
            ("Sanskrit", ""),
            ("Statistics", ""),
            ("Tamil", ""),
            ("Telugu", ""),
            ("Textile Technology", ""),
            ("Textiles and Dress Designing", ""),
            ("Urdu", ""),
            ("Zoology", ""),
        ],
    },
    "KSEAB": {
        10: [
            ("Apparel Made-ups and Home Furnishing", "21EK"),
            ("Arabic Third Language", "64A"),
            ("Automobile", "88EK"),
            ("Beauty and Wellness", "90EK"),
            ("Carnatic Music", "29E"),
            ("Economics", "96E"),
            ("Electronics and Hardware", "22EK"),
            ("Elements of Computer Science", "74"),
            ("Elements of Electrical Engineering IV", "51"),
            ("Elements of Electronics Engineering II", "73"),
            ("Elements of Electronics Engineering IV", "53"),
            ("Elements of Mechanical and Electrical Engineering II", "71"),
            ("Elements of Mechanical Engineering IV", "52"),
            ("Engineering Graphics II", "72"),
            ("English First Language", "14E"),
            ("English NCERT First Language", "15E"),
            ("English Second Language", "31E"),
            ("English Third Language", "63E"),
            ("Health Care", "89EK"),
            ("Hindi First Language", "06H"),
            ("Hindi NCERT Third Language", "60H"),
            ("Hindi Third Language", "61H"),
            ("Hindustani Music", "28E"),
            ("Information Technology", "86EK"),
            ("Kannada First Language", "01K"),
            ("Kannada Second Language", "33K"),
            ("Kannada Third Language", "62K"),
            ("Konkani Third Language", "68DK"),
            ("Marathi First Language", "08M"),
            ("Marathi Third Language", "70M"),
            ("Mathematics", "81E"),
            ("Political Science", "97E"),
            ("Programming in ANSI C", "54"),
            ("Retail", "87EK"),
            ("Sanskrit First Language", "16S"),
            ("Sanskrit Third Language", "67S"),
            ("Science", "83E"),
            ("Social Science", "85E"),
            ("Sociology", "95E"),
            ("Tamil First Language", "10T"),
            ("Telugu First Language", "04L"),
            ("Tulu Third Language", "69DK"),
            ("Urdu First Language", "12U"),
            ("Urdu Third Language", "66U"),
        ],
        12: [
            ("Accountancy", "30"),
            ("Apparel Made-ups and Home Furnishing", "60"),
            ("Arabic", "11"),
            ("Automobile", "63"),
            ("Basic Mathematics", "75"),
            ("Beauty and Wellness", "65"),
            ("Biology", "36"),
            ("Business Studies", "27"),
            ("Chemistry", "34"),
            ("Computer Science", "41"),
            ("Economics", "22"),
            ("Education", "52"),
            ("Electronics", "40"),
            ("Electronics and Hardware", "59"),
            ("English", "02"),
            ("French", "12"),
            ("Geography", "24"),
            ("Geology", "37"),
            ("Hindi", "03"),
            ("Hindustani Music", "26"),
            ("History", "21"),
            ("Home Science", "67"),
            ("Information Technology", "61"),
            ("Kannada", "01"),
            ("Logic", "23"),
            ("Malayalam", "06"),
            ("Marathi", "07"),
            ("Mathematics", "35"),
            ("Optional Kannada", "16"),
            ("Physics", "33"),
            ("Political Science", "29"),
            ("Psychology", "32"),
            ("Retail", "62"),
            ("Sanskrit", "09"),
            ("Sociology", "28"),
            ("Statistics", "31"),
            ("Tamil", "04"),
            ("Telugu", "05"),
            ("Urdu", "08"),
        ],
    },
}

# (keyword in subject name, Bootstrap icon, accent colour) — first match wins.
STYLES = [
    ("applied math", "graph-up", "#2563a8"),
    ("math", "calculator", "#2563a8"),
    ("physics", "lightning-charge", "#b45309"),
    ("chemistry", "droplet", "#7c3aed"),
    ("biology", "flower1", "#15803d"),
    ("social", "globe-asia-australia", "#9a3412"),
    ("science", "flask", "#0f766e"),
    ("computer", "pc-display", "#0369a1"),
    ("informatics", "pc-display", "#0369a1"),
    ("information tech", "router", "#0369a1"),
    ("artificial", "cpu", "#6d28d9"),
    ("account", "cash-coin", "#4d7c0f"),
    ("business", "briefcase", "#a16207"),
    ("commerce", "briefcase", "#a16207"),
    ("economics", "bar-chart", "#be123c"),
    ("history", "hourglass-split", "#92400e"),
    ("geography", "map", "#047857"),
    ("political", "bank", "#1d4ed8"),
    ("psychology", "person-badge", "#c026d3"),
    ("sociology", "people", "#db2777"),
    ("physical", "trophy", "#ea580c"),
    ("english", "translate", "#c2410c"),
]
DEFAULT_STYLE = ("book", "#475569")
POPULAR = {"mathematics", "science", "english", "physics", "chemistry", "biology", "english core",
           "accountancy"}


def style_for(name):
    lowered = name.casefold()
    return next(((icon, color) for word, icon, color in STYLES if word in lowered), DEFAULT_STYLE)
