# Generated by Django 6.0.8 on 2026-09-27 12:19

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='scans/%Y/%m/', validators=[core.validators.ImageValidator()])),
                ('typed_question', models.TextField(blank=True, help_text='Question typed instead of scanned')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=12)),
                ('extracted_text', models.TextField(blank=True)),
                ('detected_question', models.TextField(blank=True)),
                ('detected_subject_name', models.CharField(blank=True, max_length=120)),
                ('detected_topic_name', models.CharField(blank=True, max_length=200)),
                ('is_handwritten', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('concept', models.TextField(blank=True)),
                ('follow_up_questions', models.JSONField(blank=True, default=list)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('processing_ms', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='boards.chapter')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='boards.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'scanner history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_sca_user_id_d83bcd_idx')],
            },
        ),
    ]
