# Generated by Django 6.0.8 on 2026-09-27 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Demo/sample content created for development. Shown with a 'Sample' badge.")),
                ('name', models.CharField(max_length=150, unique=True)),
                ('short_name', models.CharField(help_text='e.g. CBSE, ICSE, MSBSHSE', max_length=30)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('board_type', models.CharField(choices=[('national', 'National board'), ('state', 'State board'), ('international', 'International board')], default='state', max_length=20)),
                ('state', models.CharField(blank=True, help_text='State/region for state boards', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='boards/logos/')),
                ('website', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text="Show on the homepage 'Popular boards' section")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Demo/sample content created for development. Shown with a 'Sample' badge.")),
                ('name', models.CharField(help_text='e.g. Class 10', max_length=60)),
                ('number', models.PositiveSmallIntegerField(help_text='Numeric grade, used for ordering')),
                ('slug', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='boards.board')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['board', 'order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Demo/sample content created for development. Shown with a 'Sample' badge.")),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('code', models.CharField(blank=True, help_text='Official subject code, if any', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='book', help_text='Bootstrap Icons name, e.g. calculator, flask, globe', max_length=50)),
                ('color', models.CharField(default='#4f46e5', help_text='Accent colour (hex)', max_length=7)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='boards.classlevel')),
            ],
            options={
                'ordering': ['class_level', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Demo/sample content created for development. Shown with a 'Sample' badge.")),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='boards.subject')),
            ],
            options={
                'ordering': ['subject', 'order', 'number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Demo/sample content created for development. Shown with a 'Sample' badge.")),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='boards.chapter')),
            ],
            options={
                'ordering': ['chapter', 'order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='classlevel',
            constraint=models.UniqueConstraint(fields=('board', 'slug'), name='unique_class_slug_per_board'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('class_level', 'slug'), name='unique_subject_slug_per_class'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('subject', 'slug'), name='unique_chapter_slug_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('chapter', 'slug'), name='unique_topic_slug_per_chapter'),
        ),
    ]
