# Generated by Django 6.0.8 on 2026-09-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#0f766e', help_text='Accent colour (hex)', max_length=7),
        ),
    ]
