# Generated by Django 6.0.8 on 2026-09-27 12:19

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_sample', models.BooleanField(default=False, help_text="Demo/sample content created for development. Shown with a 'Sample' badge.")),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('material_type', models.CharField(choices=[('pdf', 'PDF'), ('notes', 'Notes'), ('summary', 'Chapter summary'), ('revision', 'Revision notes'), ('formula', 'Formula sheet'), ('important_questions', 'Important questions'), ('concept', 'Concept explanation')], db_index=True, default='notes', max_length=25)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, help_text='Content in Markdown (headings, lists, **bold**)')),
                ('file', models.FileField(blank=True, upload_to='materials/%Y/', validators=[core.validators.PDFValidator()])),
                ('thumbnail', models.ImageField(blank=True, upload_to='materials/thumbs/', validators=[core.validators.ImageValidator()])),
                ('reading_minutes', models.PositiveSmallIntegerField(default=5)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='boards.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='boards.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='boards.topic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'chapter', 'material_type'], name='content_stu_subject_a2a523_idx')],
            },
        ),
    ]
