# Generated by Django 6.0.8 on 2026-09-27 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('url', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('board', models.ForeignKey(blank=True, help_text='Leave empty to notify all students', null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('material', 'New study material'), ('paper', 'New question paper'), ('test_recommendation', 'Recommended test'), ('test_reminder', 'Test reminder'), ('performance', 'Performance update'), ('announcement', 'Announcement')], db_index=True, max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
