# Generated by Django 6.0.8 on 2026-09-27 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rec_type', models.CharField(choices=[('test', 'Practice test'), ('paper', 'Question paper'), ('material', 'Study material'), ('chapter', 'Chapter to revise'), ('question', 'Practice question'), ('revision', 'Revision topic')], db_index=True, max_length=15)),
                ('object_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0, help_text='Higher = more relevant')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_dismissed', '-score'], name='recommendat_user_id_7eb29f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_recommendation')],
            },
        ),
    ]
